
apiVersion: paex/0.1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: paex
  replicas: 2
  template:
    metadata:
      labels:
        app: paex
    spec:
      containers:
      - name: paex
        image: paex:0.1
        ports:
        - containerPort: 80