# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rule_pb2 as rule__pb2


class CodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.code = channel.unary_unary(
                '/Code/code',
                request_serializer=rule__pb2.Number.SerializeToString,
                response_deserializer=rule__pb2.Number.FromString,
                )


class CodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def code(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'code': grpc.unary_unary_rpc_method_handler(
                    servicer.code,
                    request_deserializer=rule__pb2.Number.FromString,
                    response_serializer=rule__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Code', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Code(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def code(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Code/code',
            rule__pb2.Number.SerializeToString,
            rule__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
